# baseURL = ''
languageCode = 'zh'
title = 'OS Debug 文档'

# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
enableGitInfo = true

# (Optional) Theme is intended for documentation use, therefore it doesn't render taxonomy.
# You can remove related files with config below
disableKinds = ['taxonomy']

[markup.tableOfContents]
  startLevel = 1

[[menu.after]]
  name = '代码仓库（OSGDB）'
  url = 'https://github.com/OSDebugger/osgdb'
  weight = 10

[[menu.after]]
  name = '代码仓库（Async-Debuger）'
  url = 'https://github.com/OSDebugger/async-debug'
  weight = 20

[[menu.after]]
  name = '异步跟踪方案仓库'
  url = 'https://github.com/OSDebugger/code-debug_Asynchronous-trace'
  weight = 30

[[menu.after]]
  name = '开发者文档'
  pageRef = 'dev'
  weight = 40

[params]
  BookTheme = 'auto'
  BookSection = '*'
  BookRepo = 'https://github.com/OSDebugger/OSDebugger.github.io'
  BookEditPath = 'edit/main'
  BookCommitPath = 'commit'
  BookDateFormat = 'Jan 2, 2006'